hw2/task2/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('to_do_list.urls', namespace='to_do_list')),
]

hw2/to_do_list/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views


urlpatterns = [
    url(r'^$', views.ToDoListView.as_view(), name="to_do_list_list"),
    url(r'^(?P<pk>\d+)/$', views.TaskView.as_view(), name="task"),
    url(r'^new/$', login_required(views.CreateTask.as_view()), name="add_task"),
    url(r'^(?P<pk>\d+)/edit/$', login_required(views.UpdateTask.as_view()), name="edit_task"),
    url(r'^(?P<pk>\d+)/done/$', login_required(views.TaskDone.as_view()), name="task_done"),
]

hw2/to_do_list/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.


class ModelWithDates(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Task(ModelWithDates):
    title = models.CharField(max_length=255, default='')
    description = models.TextField()
    mark_as_done = models.BooleanField(default=False)

hw2/to_do_list/views.py
from django.shortcuts import render
from django.urls import reverse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, View
from .models import Task
# Create your views here.


class ToDoListView(ListView):
    queryset = Task.objects.all()
    template_name = 'to_do_list_list.html'

    def dispatch(self, request, *args, **kwargs):
        return super(ToDoListView, self).dispatch(request, *args, **kwargs)


class TaskView(DetailView):
    queryset = Task.objects.all()
    template_name = 'task.html'

    def dispatch(self, request, *args, **kwargs):
        return super(TaskView, self).dispatch(request, *args, **kwargs)


class CreateTask(CreateView):
    template_name = 'add_task.html'
    model = Task
    fields = ('title', 'description')
    mark_as_done = False

    def dispatch(self, request, *args, **kwargs):
        return super(CreateTask, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CreateTask, self).get_context_data(**kwargs)
        context['mark_as_done'] = False
        return context

    def form_valid(self, form):
        form.instance.mark_as_done = False
        return super(CreateTask, self).form_valid(form)

    def get_success_url(self):
        return reverse("to_do_list:task", args=(Task.objects.all().count(),))


class UpdateTask(UpdateView):
    template_name = 'edit_task.html'
    model = Task
    fields = ('title', 'description')

    def get_success_url(self):
        return reverse("to_do_list:task", args=(self.object.pk,))

    def dispatch(self, request, *args, **kwargs):
        return super(UpdateTask, self).dispatch(request, *args, **kwargs)


class TaskDone(UpdateView):
    template_name = 'task_done.html'
    model = Task
    fields = ('mark_as_done',)

    def get_success_url(self):
        return reverse("to_do_list:task", args=(self.object.pk,))

    def dispatch(self, request, *args, **kwargs):
        return super(TaskDone, self).dispatch(request, *args, **kwargs)

hw2/to_do_list/templates/add_task.html
{% extends "base.html" %}

<div class="content">
{% block content %}

    <section>
        <article>Создание новой задачи</article>
        <h2><a href="{% url "to_do_list:to_do_list_list" %}">Список задач</a></h2>

        <form action="{% url "to_do_list:add_task" %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="button" value="Создать">
        </form>
    </section>
{% endblock %}
</div>

hw2/to_do_list/templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <title>To do list</title>
        <link rel="stylesheet" href="{% static "base.css" %}">
        {% block extra %}{% endblock %}
    </head>

    <body>
        <div class="content">{% block content %}{% endblock %}</div>

        <footer>{% block footer %}<i>Список задач</i>{% endblock %}</footer>
    </body>
</html>

hw2/to_do_list/templates/edit_task.html
{% extends "base.html" %}

<div class="content">
    {% block content %}
        <section>
            <article>Редактировать задачу</article>

            <h2><a href="{% url "to_do_list:to_do_list_list" %}">Список задач</a></h2>
            <h2><a href="{% url "to_do_list:task" pk=object.id %}">К задаче</a></h2>

            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="button" value="Сохранить">
            </form>
        </section>
    {% endblock %}
</div>

hw2/to_do_list/templates/task.html
{% extends "base.html" %}

<div class="content">
    {% block content %}
        <nav>
            <a href="{% url "to_do_list:to_do_list_list" %}">Вернуться к списку</a>
            <p></p>

            {% if not object.mark_as_done %}
                <a class="task-edit-link" href="{% url "to_do_list:edit_task" pk=object.id %}">Редактировать задачу</a>
                <p></p>
            {% endif %}
        </nav>

        <section>

            <article><strong>{{ object.title }}</strong></article>

            <p>{{ object.description }}</p>
            <p></p>
            <p></p>

            {% if object.mark_as_done %}
                <article>Задача сделана</article>
            {% else %}
                <article>Задача еще не сделана</article>
            {% endif %}
            <a class="task-done-link" href="{% url "to_do_list:task_done" pk=object.id %}">Изменить статус задачи</a>
            <p></p>

            <p>Создана: {{ object.created }}</p>
            <p>Обновлена: {{ object.updated }}</p>
            <p></p>


        </section>
{% endblock %}
</div>

hw2/to_do_list/templates/task_done.html
{% extends "base.html" %}

<div class="content">
    {% block content %}
        <section>
            <article>Изменить статус задачи</article>

            <h2><a href="{% url "to_do_list:to_do_list_list" %}">Список задач</a></h2>
            <h2><a href="{% url "to_do_list:task" pk=object.id %}">К задаче</a></h2>

            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="button" value="Сохранить">
            </form>
        </section>
    {% endblock %}
</div>

hw2/to_do_list/templates/to_do_list_list.html
{% extends "base.html" %}

<div class="content">
    {% block content %}
        <section>
            <article><h2>Список задач:</h2></article>
            <p><strong><a href="{% url "to_do_list:add_task" %}">Создать новую задачу</a></strong></p>
            <p></p>
            {% if object_list %}
                {% for task in object_list %}
                    <div>
                        <a href="{% url "to_do_list:task" pk=task.id %}">{{ task.title }}</a>
                        <p></p>
                        <details>Описание: {{ task.description }}</details>
                        {% if task.mark_as_done %}
                            <p>Задача сделана</p>
                        {% else %}
                            <p>Задача еще не сделана</p>
                        {% endif %}
                    </div>
                    <p></p>
                {% endfor %}
            {% else %}
                <header><strong>Задач пока нет</strong></header>
            {% endif %}

        </section>

    {% endblock %}
</div>